### ISSUE TITLE
Will give me an url like localhost/?daasda@domain.com

### ISSUE THREAD

**Issue by cChimney** [pfeifferch/disposable-mailbox#2]
Like title says, Will give me an url like localhost/?daasda@domain.com but the page itselfs is blank??!

**Comment by pfeifferch** [comment]
V 2.5.34 BETA ? 


All the steps
 Requirements
 Before you start
 installation
 Troubleshooting
observed?


Which operating system, which PHP version, version of Apache?
 Is the source text of the page also empty in the browser?

**Comment by cChimney** [comment]
Yes, the source code is also empty. I'm gonna check which ver im using rn hold on. Im using xxamp btw

**Comment by cChimney** [comment]
PHP 7.4.24

**Comment by pfeifferch** [comment]
controller.php

$address = User::get_random_address($config{'domains'});
       

Please change line 58 in the controller.php, as it is above
